### PR TITLE
Section convert: trains

### PR DESCRIPTION
**Pull request by s520**
Once we convert trains section, you are ready to merge this PR.

Please wait...

### CODE REVIEW

**Comment by s520** [comment]
content/en/trains/extensions_cfg/_index.md
- Broken link: https://openbve-project.net/documentation/HTML/information_folderstructure.html

**Comment by leezer3** [comment]
I'm not sure that page ever worked looking into my archive...
My archjve copy of the original openBVE site was saved by me directly, and it's 404 there.
The Internet Archive hasn't saved it either on the original Trainsimcentral URL or the later Trainsimframework URL.

**Comment by s520** [comment]
It seems to be a page that explains the structure of the train folder.

Since it does not exist in Internet Archive, will you create it in the future?

**Comment by MarcRiera** [comment]
I have found it in Internet Archive but in the archived version of Odakyufan's website, which included  a compressed folder with the documentation: https://web.archive.org/web/20131031075802/http://odakyufan.zxq.net/openbve/documentation.7z

Not sure if it is really useful, but at least it is not lost.

**Comment by leezer3** [comment]
It's not in that archive either :/

We could recreate the page easily, but trains have no specific folder structure whatsoever (All it checks for is the presence of the train.dat and the specified sounds in this route folder if the sound.cfg file is not present), so it might be more useful to just discard the page entirely...

**Comment by s520** [comment]
I completed converting other than the item of "The train.xml file".

Please merge this PR.

However, since there is no original in this item, please create it.

**Pull request merged**
