### PR TITLE
Responsive Mobile Layout

### PR DESCRIPTION
**Pull request by zbx1425**
Several changes to make the documentation more accessible.
- Responsive layout
  This makes the website able to be browsed smoothly from a mobile device. Although the UI is not quite artistic, it is usable.
- Change sidebar navigation link color
  The color of the sidebar navigation links is changed to a darker one, to add contrast and improve readability.
- More compact warning-nontitle layout
  The empty but very red title line of warning-nontitle blocks are replaced with a little icon. This improves the readability and color combination of the page, considering there are many of them.
- More obvious language selection button
  Several of my friends complained they had difficulties finding the language selection button located at the corner of the page. So a brighter color is used on the button to make it easier to spot.

### CODE REVIEW

**Comment by zbx1425** [comment]
To preview the changes please see https://api.zbx1425.tk:8953/obve_hugo .

**Comment by leezer3** [comment]
Very nice from a brief poke on the phone. (The current isn't too bad either, but it's an expensive phone.....)

Will play later.

**Comment by zbx1425** [comment]
> Very nice from a brief poke on the phone. (The current isn't too bad either, but it's an expensive phone.....)

Wait a sec.
The language list currently overflows the screen of a phone with not a very high resolution.
Trying to fix that...

**Comment by zbx1425** [comment]
Well, it does not seem quite nice-looking, I think... But at least it can scroll and let the user choose the desired language if the list overflows the screen.

**Comment by zbx1425** [comment]
Nope, resolving one problem brings one another.
Oh gosh... I hate css.

**Comment by leezer3** [comment]
Yep :p

TBQH I think any mobile availability is a bonus.
I certainly wouldn't want to view the docs on a phone.

**Comment by zbx1425** [comment]
This should finally solve the problem.
Maybe moving the inline javascripts into an individual file would be a nice idea to save space since it duplicates between files. It is not much code though.

**Comment by s520** [comment]
Thanks for a great suggestion.

I looked at the demo page using a PC and a smartphone.

Regarding the language button on the smartphone, how about incorporating it into the side menu?
By doing so, I think the location is easy to understand and I think that it looks good even on a smartphone.

**Comment by zbx1425** [comment]
> Regarding the language button on the smartphone, how about incorporating it into the side menu?
> By doing so, I think the location is easy to understand and I think that it looks good even on a smartphone.

It's done!

**Comment by s520** [comment]
Great!

If you can put JavaScript into `themes/openbve_documentation/static/script/script.js`, I think it's better to do it.

Also, it seems that incorporating a language list into the side menu on a PC can simplify the code.
(Earlier I wrote "on a smartphone". This was a mistake. I'm sorry.)

**Comment by s520** [comment]
I submitted the suggestion above as a pull request.
https://github.com/zbx1425/OpenBVE-Documentation-Hugo/pull/1

**Comment by zbx1425** [comment]
> I submitted the suggestion above as a pull request.

Well, sorry! I failed to notice your PR and tried to implement the feature by myself.
Please take a look.

Also, I implemented a feature that makes use of javascript to automatically switch to the prefered language given by the browser of the viewer.

**Comment by s520** [comment]
No problem :)
Your implementation looks better than mine.

I think that the contents of language.html should be moved to header.html or renamed.
It is better to rename the contents of bulma.custom.css. (`#language-menu`)

**Comment by zbx1425** [comment]
I am trying to get rid of bulma.custom.css, since we are not using that language picker control anymore.
However I got into some problem with the css `position:fixed` attribute.

**Comment by s520** [comment]
bulma.custom.css is used for the appearance of the menu button.
https://github.com/leezer3/OpenBVE-Documentation-Hugo/pull/16/files#diff-75c7db04981082612848b0fcf8680091R1-R3

Please check the elements in your browser's developer tools.

**Comment by s520** [comment]
Note the red circle.
elements

**Comment by zbx1425** [comment]
I am aware of that, and I am trying to copy associated code into the theme.css file.
But I had some problem with positioning the floating menu button.

**Comment by s520** [comment]
I split css files to keep track of where the code came from.

I will look into location issues from tomorrow.

**Comment by zbx1425** [comment]
> I split css files to keep track of where the code came from.
I prefer merging the bulma.custom.css into themes.css, because most of its functionality is not used. And we can just write a class for a floating action button.
> I will look into location issues from tomorrow.
I think the major problem is to prevent the body from overflowing the viewport on X direction. It seems the major problem is about the wide tables that won't fit. I will try to apply a horizontal scrollbar wrapper to it.
In chrome, although the button disappears when scrolling downwards, it reappears when scrolling upwards, which is actually acceptable. I am actually a bit prefering not fixing it.

**Comment by zbx1425** [comment]
This is now fixed. I also added some nice jquery animation to the sidebar.

**Comment by zbx1425** [comment]
But this raises another problem: Erroratic Tag at line 343 of content/en/objects/native/animated/_index.md
The table at this position is missing a end tag. The line 343, which is string#144 at transifex, is:
```
328 ##### ● Comparisons
329 
330 All comparisons return 1 for true and 0 for false.
331
332 {{% table %}}
333
334 | Infix    | Functional          | Description                                     |
335 | :------- | ------------------- | ----------------------------------------------- |
336 | `a == b` | `Equal[a,b]`        | True (1) if *a* equals *b*                      |
337 | `a != b` | `Unequal[a,b]`      | True (1) if *a* does not equal *b*              |
338 | `a < b`  | `Less[a,b]`         | True (1) if *a* is less than *b*                |
339 | `a > b`  | `Greater[a,b]`      | True (1) if *a* is greater than *b*             |
340 | `a <= b` | `LessEqual[a,b]`    | True (1) if *a* is less than or equal to *b*    |
341 | `a >= b` | `GreaterEqual[a,b]` | True (1) if *a* is greater than or equal to *b* |
342
343 {{% table %}}
```
which should have been `{{% /table %}}`, and messed up the entire DOM.
I have included a fix in the previous commit

**Comment by s520** [comment]
It looks much better than in the early days.
I think that it is easy to operate even with a smartphone.

Please correct the English version about `{{% /table %}}` .
If Mr. leezer3 merge this PR, it will be synchronized with Transifex.
(The correction is applied to all languages.)

**Comment by zbx1425** [comment]
Uh-oh.
I thought I fixed the English content, but it turned out zh_CN was edited instead.
Stupid mistake! hhh

**Comment by zbx1425** [comment]
position: fixed broke again. On firefox this time. What the HELL.
I think maybe I need some professional assistance.
Screenshot_2020-03-16-00-29-05

**Comment by leezer3** [comment]
Definitely getting better.

Something else to be added as part of this (?)-
Is a notice that all parts of the documentation may not be fully translated a good idea for the front page?

**Comment by zbx1425** [comment]
That is a good idea.
I think we can also remove the "Please note that some of these pages are still under construction." list, since there are far more unfinished page than this list, and the CSV route format page is already finished. 
Maybe change it to something like "Please note that some of these pages are still under construction, and some pages are not yet translated." ?

**Comment by leezer3** [comment]
Good point.

The 'under construction' stuff is primarily third-party object formats.
Exactly how much we should document these is unclear (Is it really the place of our documentation to describe the X format in detail? Probably not......)

Doing some more work on the object formats is on the list for when I get a little more time- Now we've implemented matrix based rotations, getting the X and MSTS keyframe animations working should be do-able.

**Comment by zbx1425** [comment]
I think maybe we should also plan to add some more developer-friendly animation syntaxs for the .animated objects, maybe keyframes or something. Quite a few of my friends complained having a hard time figuring out the correct formula, especially when considering damping, delays and other elements... I even made a calculator at https://www.zbx1425.tk/obvemainsite/doorzfunc.html to help doing such difficult calculations.
By the way, It seems that I succeed in locating the problem. It seems that it is caused by a extra closing tag in the document that broke the entire DOM again, and broke everything... Going to take a look at the cause later.

**Comment by zbx1425** [comment]
I fixed the aforementioned problem.
Also, I tried to add a special shortcode, `{{% table-2col %}}` for tables with 2 columns to have a better appearance on mobile devices. Like this: 
localhost_obve_hugo_public_en_objects_native_animated html(Pixel 2)

**Comment by s520** [comment]
Thank you for your hard work.

Regarding `{{% code %}}`, I think that it is hard to see because the code wraps on a smartphone.
It is better to scroll to fit the width of the screen.

---

> I think maybe we should also plan to add some more developer-friendly animation syntaxs for the .animated objects, maybe keyframes or something. Quite a few of my friends complained having a hard time figuring out the correct formula, especially when considering damping, delays and other elements... I even made a calculator at https://www.zbx1425.tk/obvemainsite/doorzfunc.html to help doing such difficult calculations.

This is an off-topic topic, some .animated functions allow you to specify a script file.
https://github.com/leezer3/OpenBVE/blob/44271253209840bc7fb41530da21a5eb1012ca0f/source/OpenBveApi/Objects/ObjectTypes/AnimatedObject.cs#L279-L307

This script file is written in C#, so it may not be easier than usual notation.

**Comment by zbx1425** [comment]
You can see that I have actually tried to make the `{{% code %}}` become no-wrap. But while perserving the formats, it also makes reading more difficult, since it forces you to scroll from leftmost to rightmost, and then right to left, to read every single line, and would be really hard for a long piece of code. So it is actually not quite easy to decide which way is better.

**Comment by s520** [comment]
As you say, displaying on a single line may require long scrolling, but more than that, I'm afraid that the code wraps and looks like two lines.
If we look at the two lines, we may give the wrong information to the viewer...

However, if we can make it not to look like two lines, it's okay to wrap it.

**Comment by zbx1425** [comment]
It is done. All code and font tags (The really outdated font tags are used for coloring and codes in the documentation. As coloring often only affects a single word, making it also no-wrap seems will not cause a problem.) will be no-wrap.
Also I made a minor tweak on the language list, so it will expand by default if jQuery failed to load. This should make the website accessible on browsers with no or poor javascript support.

**Comment by zbx1425** [comment]
Also @s520 BTW, I would like to know where these arts of various people come from:
Art
It seems that they are widely used in quite a few presentations in Japan, but not regularly used anywhere else! These clip arts seems really impressive.

**Comment by s520** [comment]
Thank you for handling the code wrapping.

---
The clip art I used is available at the following site.
https://www.irasutoya.com/

What is distributed here can be used free of charge for personal, corporate, commercial or non-commercial use.
Note, however, that copyright has not been relinquished.

**Comment by zbx1425** [comment]
Thanks a lot!

-----
I think this PR should be mergeable by now.
Will open another one if something breaks after that...

**Comment by zbx1425** [comment]
Holy cow... It breaks down instantly.
My bad, my bad. Silly mistake.
The automatic language switching code tries to determine the new url, by simply replacing the current language in url to target language. Such as `en/index.html` becomes `zh_cn/index.html`.
But unfortunately I forgot to add some special check on directories, and it replaced the `en` in `op"en"bve-project.net` instead... And returned a url like `https://opzh_cnbve-project.net/documentation_hugo/en/`, which is completely nonsense.
Will try to commit a quick fix on that.

**Comment by s520** [comment]
Changing as follows will solve the problem.
https://github.com/OpenBVE-JapaneseTeam/OpenBVE-Site-Japan/commit/c7fa944ae4499eb1c78a266fb918b7dd6b8c51e7

If you fix it, give priority to your PR.

**Comment by zbx1425** [comment]
I am thinking of the possibility of the final slash not being added when accessing the root directory of a language directory, such as `documentation_hugo/en`. Will it happen and make this script fail to detect the baseURL?
Also just in case there is a subfolder which accidentally has a name of a language...
I am trying to figure out a way to solve this. Maybe let the script determine the path relative to the parent folder by the link generated by `<link rel="icon" href="{{ .Site.BaseURL }}/favicon.png">`, seems a better idea.

**Comment by s520** [comment]
OK.
I wait for your correction.

By the way, in the future, it may be better to review the pages generated by Hugo when the PR is submitted.

**Comment by zbx1425** [comment]
I have written the code, tested locally and hope it is fixed...
I will open another PR for this.

**Pull request merged**
