### PR TITLE
Change:add explanation of TrackFollowingObject

### PR DESCRIPTION
**Pull request by ginga81**
When I translating this contents, I think that we should add to the sentence about TFO.
So, I changed this sentence.

### CODE REVIEW

**Comment by s520** [comment]
@leezer3 
Please check this.

**Comment by leezer3** [comment]
Oops, this got forgotten....

**Comment by s520** [comment]
Thanks!

**Comment by ginga81** [comment]
Thank you very much for merged my first PR of my life!

**Pull request merged**
