### PR TITLE
Section upgrade: routes

### PR DESCRIPTION
**Pull request by MarcRiera**
I have begun upgrading the "Routes" section of the documentation to Markdown. For now I have only converted the RW page and its quick reference counterpart.

Once the whole section is done, the pull request will be ready to merge.

### CODE REVIEW

**Comment by s520** [comment]
The "Routes" section is quite large.

Would you like some help?

**Comment by MarcRiera** [comment]
I agree that it is quite a lot, so feel free to help if you want. I am currently working on finishing the CSV route page and the ATS tutorials, so the XML pages (markers, lighting, etc.) are free.

Thanks a lot!

**Comment by s520** [comment]
OK.
I will start working. :+1:

**Comment by s520** [comment]
I have completed the conversion of the XML pages.

By the way, have you completed "Tutorial: Using ATC"?

I will be in charge if it is not completed.

**Comment by MarcRiera** [comment]
I am halfway done with the ATS and ATC tutorials, and I think I will have finished them later today.

**Comment by s520** [comment]
I understand.

Now it will end the conversion of all of the items.

We can work on CSS coordination and translation!

**Comment by MarcRiera** [comment]
This is now ready to merge. I have also defined the UTF-8 encoding in the header.html partial template for automatic browser detection, which in theory should prevent display errors.

**Comment by s520** [comment]
@leezer3  https://github.com/leezer3/OpenBVE/issues/304#issuecomment-460041862

**Pull request merged**
